version: 0.2
phases:
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - mv target/proj2-spring-0.0.1-SNAPSHOT.jar proj2-spring-0.0.1-SNAPSHOT.jar
  artifacts:
    files:
    - proj2-spring-0.0.1-SNAPSHOT.jar